version: "3"
services:
  food-delivery-config-server:
    container_name: food-delivery-config-server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.256'
          memory: 512M
        reservations:
          cpus: '0.128'
          memory: 128M
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - profile.env
    ports:
      - 8888:8888
    networks:
      - food-delivery-net

networks:
  food-delivery-net:
    driver: bridge
