spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://116.206.127.212:5432/customer
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mypassword}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8093