#eureka:
#  instance:
#    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
#    lease-renewal-interval-in-seconds: 100
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://${eureka.instance.hostname}:${server.port}/eureka}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://116.206.127.212:5431/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mypassword}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mypassword}
server:
  port: 8091