spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://116.206.127.212:5432/order}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mypassword}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    customer-url: ${CUSTOMER_URL:http://localhost:8222/api/v1/customer}
    rider-url: ${RIDER_URL:http://localhost:8222/api/v1/rider}
    restaurant-url: ${RESTAURANT_URL:http://localhost:8222/api/v1/restaurant}
server:
  port: 8091