spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://116.206.127.212:5432/restaurant}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mypassword}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8094